In [2]:
from tensorflow.keras.preprocessing.text import one_hot  # type: ignore

In [5]:
# Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [15]:
# Define the vocabulary size
voc_size = 10000

In [16]:
# One hot representation
one_hot_repr = [one_hot(word, voc_size) for word in sent]
one_hot_repr

[[994, 1957, 4138, 5193],
 [994, 1957, 4138, 2554],
 [994, 7390, 4138, 5116],
 [457, 2130, 6984, 1075, 9635],
 [457, 2130, 6984, 1075, 9896],
 [7385, 994, 1529, 4138, 5332],
 [1090, 2806, 9765, 1075]]

In [21]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding  # type: ignore
from tensorflow.keras.utils import pad_sequences  # type: ignore
from tensorflow.keras.models import Sequential  # type: ignore
import numpy as np

In [31]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0,  994, 1957, 4138, 5193],
       [   0,    0,    0,    0,  994, 1957, 4138, 2554],
       [   0,    0,    0,    0,  994, 7390, 4138, 5116],
       [   0,    0,    0,  457, 2130, 6984, 1075, 9635],
       [   0,    0,    0,  457, 2130, 6984, 1075, 9896],
       [   0,    0,    0, 7385,  994, 1529, 4138, 5332],
       [   0,    0,    0,    0, 1090, 2806, 9765, 1075]], dtype=int32)

In [32]:
# Feature Representation
dim = 10

In [35]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape = (sent_length, )))
model.compile('adam', 'mse')

d:\Code\AI-Bootcamp\Projects\6_Movie_Review\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:126: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [36]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step


array([[[-8.98744911e-03, -2.33704690e-02, -3.49358544e-02,
          9.74810123e-03,  3.64012383e-02, -1.04132891e-02,
          3.48542370e-02, -4.27923203e-02,  1.52201690e-02,
         -1.08390450e-02],
        [-8.98744911e-03, -2.33704690e-02, -3.49358544e-02,
          9.74810123e-03,  3.64012383e-02, -1.04132891e-02,
          3.48542370e-02, -4.27923203e-02,  1.52201690e-02,
         -1.08390450e-02],
        [-8.98744911e-03, -2.33704690e-02, -3.49358544e-02,
          9.74810123e-03,  3.64012383e-02, -1.04132891e-02,
          3.48542370e-02, -4.27923203e-02,  1.52201690e-02,
         -1.08390450e-02],
        [-8.98744911e-03, -2.33704690e-02, -3.49358544e-02,
          9.74810123e-03,  3.64012383e-02, -1.04132891e-02,
          3.48542370e-02, -4.27923203e-02,  1.52201690e-02,
         -1.08390450e-02],
        [-4.53687832e-03,  9.21947882e-03,  1.20661259e-02,
          1.63037069e-02,  1.81865357e-02,  3.93324979e-02,
          3.07655223e-02,  4.00676169e-02,  3.943313

In [38]:
embedded_docs[0]

array([   0,    0,    0,    0,  994, 1957, 4138, 5193], dtype=int32)

In [42]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[-8.9874491e-03, -2.3370469e-02, -3.4935854e-02,  9.7481012e-03,
          3.6401238e-02, -1.0413289e-02,  3.4854237e-02, -4.2792320e-02,
          1.5220169e-02, -1.0839045e-02],
        [-8.9874491e-03, -2.3370469e-02, -3.4935854e-02,  9.7481012e-03,
          3.6401238e-02, -1.0413289e-02,  3.4854237e-02, -4.2792320e-02,
          1.5220169e-02, -1.0839045e-02],
        [-8.9874491e-03, -2.3370469e-02, -3.4935854e-02,  9.7481012e-03,
          3.6401238e-02, -1.0413289e-02,  3.4854237e-02, -4.2792320e-02,
          1.5220169e-02, -1.0839045e-02],
        [-8.9874491e-03, -2.3370469e-02, -3.4935854e-02,  9.7481012e-03,
          3.6401238e-02, -1.0413289e-02,  3.4854237e-02, -4.2792320e-02,
          1.5220169e-02, -1.0839045e-02],
        [-4.5368783e-03,  9.2194788e-03,  1.2066126e-02,  1.6303707e-02,
          1.8186536e-02,  3.9332498e-02,  3.0765522e-02,  4.0067617e-02,
          3.9433133e-02, -1.1754729e-02],
        [ 1.1727750e-02, -4.5206659e-03, -3.7336566e-02,  1.